### ISSUE TITLE
Complete updates to QuestionStore for Numeric Questions

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1300]
This is for the #1298 branch (issue/554**b**)

QuestionStore now has question:setResponse and question:sendResponse and question:forceSendAllResponses. This uses the new Common.util.timeoutPromise, which creates a promise that automatically rejects after a given amount of time. I'm not convinced that it's working as expected, however I haven't had enough time to test it and ensure it's working. I want to make sure that the setResponse and sendResponse functions are working as expected and are fault tolerant on flaky connections.

**Comment by vutoan1245** [comment]
Not sure if I am correct here.
I see that `timeoutPromise` is used in `question:forceSendAllResponses` and `question:sendResponse`. However, since we don't catch the timeout rejection, the result is still the same regardless if we use or don't use it.

For example:
```
    timeoutPromise(SEND_RESPONSE_TIMEOUT_MS, sendResponsePromise)
    this.triggerChange()
```
In this case, even if it timeout, triggerChange is still being called and sendResponsePromise will keep running.

**Comment by zachberry** [comment]
@vutoan1245 I admit I'm a little unclear myself. I want to test that, for example, in the `question:sendResponse` flow if `sendResponse` timeouts will it get to the `catch` at line ~550? The hope for `timeoutPromise` is that I could wrap any async function around it and have it automatically reject the promise after not hearing anything for a set amount of time. So it may need to be tweaked to make that to work
