### ISSUE TITLE
KeyDownUtil.breakToText doesn't produce expected behavior when handling a non-collapsed selection

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1482]
You can test this by creating a few Headings, then select a portion of those and hitting enter.

```
Hea[ding text

Heading text

Heading te]xt
```

(`[...]` represents the text selection)

My expectation is when hitting enter the portion between `[...]` will be deleted, the top and bottom heading merged, then the remaining portion after the selection split off and converted into a regular text node:

```
Hea

|tx (<-- This would be regular text)
```

(`|` represents the cursor)

Perhaps we need to change the behavior of breakToText such that it allows Slate to function normally, then it simply converts the last node to a Text chunk type node.

**Comment by jpeterson976** [comment]
It seems like Slate is making it so breakToText is called once for every node that's part of the selection instead of just once for the entire selection, which I think is the main hurdle here. So this might be a Slate issue, but I'll leave that to someone more familiar with Slate to determine for sure.

This is what I think happens when you hit enter based on my experimentation:
1. Converts all nodes in selection to regular text nodes
2. Deletes highlighted portion of very first node in selection
3. Collapses cursor to end of selection, does not delete any other part of the selection that is not in first node
4. Splits last node in selection at the cursor location, which is now at the previous selection endpoint

It also throws the "cannot get leaf node at path [0,0]" error if the first selected node is the first one on the page, which I'm pretty sure is the same error that's come up in some other recent issues.
