### ISSUE TITLE
Youtube input loses focus when typing and help popup is active

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1691]
#1234 added some nice youtube functionality but this little issue came with it.

Steps to reproduce:
1. Click on `?` to open the help menu (so that it stays open)
2. type into video url input

![2021-02-23 18 42 29](https://user-images.githubusercontent.com/73480/108923658-34f12680-7607-11eb-82c9-e512feff4dbb.gif)

**Comment by zachberry** [comment]
Pretty sure this has to do with more-info-button.js:

```js
componentDidUpdate() {
	if (this.state.mode === 'clicked') {
		this.dialogRef.current.focus()
	}
}
```

It takes the focus when you click on it so it'll be read by screenreaders, the issue is that once it's in 'clicked' mode (meaning its open) it'll keep taking focus away on every update. We just need to change it so that we only steal the focus when transitioning from not 'clicked' to 'clicked'
