### ISSUE TITLE
`id` in (...) menu too easy to accidentally edit

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1701]
The most common case of opening the (...) menu is to edit page titles - when you're moving quickly it's very easy to accidentally put your title in the id field (since it's the first item focused on when the dialog opens).

I'm thinking we hide the ID away in a click, so they have to click a link button to edit the ID. Since most authors won't want to mess with the id, it'll also help clean up the dialog since the id can look intimidating in it's normal UUID format.

**Comment by jpeterson976** [comment]
Here's a mockup of my initial thoughts on how this would look. ID input is disabled by default so it can't be accidentally edited, and is enabled if the "Edit" button is clicked to show basically the current UI. Clicking "OK" will then toggle back to the disabled view. I removed the "Copy Id" button in the edit mode so the input box wouldn't be as restricted in size, since it felt too small with two buttons.

<img width="691" alt="Screen Shot 2021-06-01 at 11 52 13 AM" src="https://user-images.githubusercontent.com/46502440/120354679-a1e41e80-c2d0-11eb-9927-9e86f097d453.png">
<img width="713" alt="Screen Shot 2021-06-01 at 12 00 52 PM" src="https://user-images.githubusercontent.com/46502440/120355201-18811c00-c2d1-11eb-8f89-8ed685f96466.png">

**Comment by zachberry** [comment]
I like this! I'm all for it.
