### ISSUE TITLE
Iframe initial zoom values not being respected in specific cases

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1737]
The issue is due to the fact that the IFrame constructor is calling MediaUtil.setDefaultZoom. If you happen to have a page of IFrames followed by a page of IFrames, and switch between pages, the second page of IFrames won't call MediaUtil.setDefaultZoom.

Instead, we should move the MediaUtil.setDefaultZoom call into componentDidMount (will need to test to make sure this still works with IFrames with autoload=true)

**Comment by maufcost** [comment]
I am working on it now, and it seems it needs a little bit more of work than moving MediaUtil.setDefaultZoom from the constructor to componentDidMount.

As far as my testing goes, all the iframes after the first one are not being properly mounted and unmounted (they keep mounted even when users change pages). I am investigating further what's happening.

**Comment by maufcost** [comment]
I just would like to share some more findings.

- At first, iframe 1 and iframe 2 are mounted when the module is first loaded on page 1.
- When you go from page 1 to page 2, only the extra iframe 5 is mounted (the iframe 1 and 2 keep mounted and their data 
- is just updated with iframe 3's and iframe 4's).
- However, if you go from a page with no iframes, such as page 3 to either page (1 or 2), the iframes are properly mounted and unmounted.

That's why I believe that the issue must be outside the iframe chunk - on whatever's loading the chunks. If anyone has any thoughts, let me know!
![obo](https://user-images.githubusercontent.com/39862359/112483646-9c59dd80-8d4f-11eb-9c43-62c7c24373e1.png)
