### ISSUE TITLE
extra credit sliders not updating max attempts

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1744]
When changing the attempt count from unlimited to 5, the extra credit sliders don't adjust the maximum attempts unless the user clicks on a different page, then returns to assessment

1. open a module with unlimited attempts
2. navigate to assessment
3. open extra credit, slide sliders around (choose 20)
4. hit ok
5. edit the attempt limits to 5
6. open extra credit, slide sliders around (should have upper bounds of new limit)
7. hit ok
8. navigate to a different page
9. navigate to assessment
10. observe extra credit sliders now have updated attempt limit

**Comment by zachberry** [comment]
Want to confirm if this is still an issue after #1650

**Comment by jpeterson976** [comment]
Tested on dev/22, seems to be more or less fixed by moving to the modal. Going from 5->unlimited attempts it'll still say `last attempt` until the slider is clicked again, but then the slider values will update to what they should be. Unlimited->5 attempts will say `20` in the preview but will update to `last attempt` once the edit button is clicked without needing to click on the sliders.

**Comment by zachberry** [comment]
@jpeterson976 Thanks! Marking as resolved, we can reopen if needed
