### ISSUE TITLE
Fix Share and Delete Permissions for Modules

### ISSUE THREAD

**Issue by deundrewilliams** [ucfopen/Obojobo#1983]
Currently, if an instructor (Instructor 1) creates a module and shares it with someone else (Instructor 2), Instructor 2 is able to share and edit that module. The option to delete appears for Instructor 2, but clicking the button just closes the modal without deleting anything. Since Instructor 2 can share that module, they can also take away anyone's access, including Instructor 1. If Instructor 1 no longer has access, that module can't be deleted by anyone, since currently a module can only be deleted by its creator. So, there seems to be at least two options:

1. Don't allow users to change sharing permissions of a module that they don't own, and disable/hide the sharing and deleting buttons for these users. This could also just be to don't allow users to remove access from the module owner.
2. Allow any user to delete any module that is shared with them

**Comment by FrenjaminBanklin** [comment]
My first thought is to go with option 2, since it's currently possible for any user with access to a module to remove any other user's access to that module which is not significantly different from 'deleting' the module for those users. Option 1 would certainly be possible in the short term, but it would basically mean that non-creator users would only be able to edit a module or make a copy of it (aside from viewing assessment stats).

A more ideal solution to this would be to allow different levels of access:
Full (can view stats, copy, edit, share, delete)
Partial (can view stats, copy, edit)
Minimal (can view stats, maybe copy)
A module's creator would immediately be granted 'Full' access. If we went with a more complicated scheme like this, we'd have to add a new column to the `repository_map_user_to_draft` table to track the access levels and we'd obviously have to make changes to the share dialog to present the options. We could also hide/disable module options according to access.
