### ISSUE TITLE
Numeric questions with an answer of '0' can not have a percentage margin of error.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Obojobo#2012]
It looks like there's a check in the viewer for this scenario (which throws a fatal error which results in a white screen), but there's no check in the editor to prevent it.

Speculative fixes:
1. Allow this in the editor, change the error detection in the viewer so it doesn't break everything when it happens.
2. Whenever the answer type, correct answer, or margin of error type are changed on a numeric answer, check all three - if the correct answer is zero and the margin of error type is 'Percent', put some kind of indicator in the editor to point out that this is a problem.
    a. This should also prevent the module from being saved, and probably also create an `alert` pointing out the problem so authors don't miss it.
3. Whenever the correct answer of a numeric question is zero, remove the 'Percent' option from the 'Error Type' dropdown. If the 'Error Type' value is currently set to 'Percent', it should be automatically set to 'Absolute' - make sure this is reflected accurately in the JSON/XML for the module.

**Comment by deundrewilliams** [comment]
It seems that this also happens when a range is invalid (start is >= end). An error tooltip does pop up in this case (due to the changes [here](https://github.com/ucfopen/Obojobo/pull/1784), but saving is still allowed. So opening an assessment in this state also results in the fatal error with a white screen. It seems like the best choice would be to 1) add margin of error validation similar to range validation and then 2) implement some way of preventing saving while there is an existing error of this type in the document.

**Comment by deundrewilliams** [comment]
fixed with #2027
