### ISSUE TITLE
Numeric answer validation doesn't detect shorter non-numeric strings

### ISSUE THREAD

**Issue by deundrewilliams** [ucfopen/Obojobo#2030]
When entering a non-numeric answer for a numeric question, a form validity element should show saying 'Not a valid numeric value' when trying to leave focus. This seems to work, but only for strings with at least 7 characters. 

This also still allows saving which results in a blank screen error when opening the viewer, but this part should be fixed with #2027
![numeric](https://user-images.githubusercontent.com/41072160/192528004-c1dfef77-ccf1-435e-83ea-f20eea55ec32.gif)

**Comment by deundrewilliams** [comment]
Looking at this more, it seems like saving doesn't cause a blank screen error in the viewer if the string is less than 7 characters, but the assessment grading then tries to take a margin of error of a string.

<img width="827" alt="Screen Shot 2022-09-27 at 9 40 24 AM" src="https://user-images.githubusercontent.com/41072160/192542437-d9fd57d7-e577-427a-9009-74934014e9b5.png">

**Comment by zachberry** [comment]
The input tries to do some guessing on what you mean - it may be interpreting `abcdef` as hex (as in `0xABCDEF`). I would try `xyz` as a three letter input and see if that has the same result.

**Comment by deundrewilliams** [comment]
@zachberry Oh that makes sense, trying `xyz` does result in the blank screen error instead, so it's probably interpreting it in hex

**Comment by FrenjaminBanklin** [comment]
Given the description of the issue and the knowledge that hex values are valid numeric answers, I'm not sure if there's really an 'issue' here per se.

I could see taking the 'valid inputs' tooltip from the viewer side and also placing it in the editor side so authors are immediately aware of what constitutes valid input for a numeric answer, but I'm not sure if there's anything necessary beyond that. Changing what counts as 'valid' at this point seems like it would cause breakage in existing content, so I wouldn't consider that an option.

@zachberry Curious if you think there's anything else we can or should do here. I'm hesitant to mess with the numeric validation code at all, but perhaps it would be possible to change the input in some way to indicate when a provided value is being identified as 'hexadecimal', since it's otherwise not obvious why 'xyz' is invalid but 'abc' isn't.

**Comment by zachberry** [comment]
@FrenjaminBanklin The eventual plan was to expose some options in the editor to let authors specify what types of input they expect - there's code to define that in the system but no UI to do so. I'm not sure how the bug came up, but personally I would let it ride as I would expect 'abc' not to be a common answer in a real assessment (just in cases where a dev or instructor is filling in dummy data, although I get that the result shown is confusing).

It would be possible to change the default so that it doesn't try to guess at hex-like strings and would require the prefix always (`0x` or `#`). Technically that would break existing behavior but I'm guessing adoption for numeric questions may be small enough for now that there's no instructors using it for hex, octal or binary input. The reason it does guessing (or at least the thought) was to have a question expect the student to answer in hex and be able to not require them to put in the prefix. But the result shown here in current usage probably happens way more often. If you are interested in changing that let me know and I can review the code (it's been a while), and give out some pointers on how it'd be done.
