### ISSUE TITLE
Optimize / reduce database size for assessment attempts

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#227]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 14, 2018 at 16:32 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/229_

----

Attempts keep a significant amount of data. Need to investigate if this data can be reduced / streamlined.

**Comment by samuel-belcastro** [comment]
# Analysis
The original `attempts` table in Obo's database stores a field called **state** for each assessment saved. The **state** field keeps track of the questions and question banks used for that student's attempt at the assessment, so the student can experience new questions on different attempts. The state field looks like this:
```
{
    qb: a tree rooted at the highest level question bank of an assessment node (very large)
    data: unused object
    questions: json version of each obo question used in the assessment attempt
}
```
Both the **qb** and **questions** fields store the *toObject()* version of the Obo nodes representing these questions and question banks. Since the **qb** starts at the highest level question bank of an assessment, **questions** holds duplicate question data. Both objects hold extraneous data (such as headings) that is not relevant to the function of the **state**.

Finally, the algorithm utilizing the **state** data only needs the id and type of the Obo nodes to select new questions for a new assessment attempt

# Solution
The size of the `attempts` table can be significantly reduced by only storing the id and type of the questions and question bank nodes used, and getting rid of the unused **data** field. The new **state** object looks like this:
```
{
    chosen: an array holding the id and type of question and qb nodes used in the assessment
}
```
Changing the **state** object requires changes to both the server side and client side code for assessments. These changes are branched from @qwertynerd97 branch [qwertynerd97:issue/384-modular-quiz-generation](https://github.com/qwertynerd97/Obojobo/tree/issue/384-modular-quiz-generation). This branch modularizes assessment generation, making the quiz generation process easier to understand and modify.

### Code Changes

1. Enable question banks to add themselves to their chosen question arrays when selecting questions for an assessment.
```
    // Chosen children is a list of question ids the question bank selected based the selection method
    // and how many times a question has been used
    const chosenChildren = this.buildFromArray(chosenIds, questionUsesMap)

    const thisQb = this.toObject()
    chosenChildren.push({ id: thisQb.id, type: thisQb.type })
```
2. Instead of recursing through the old **qb** tree to count how many times a question is used, iterate over the chosen questions array, and count. The usedQuestionsMap was already mapping *id* to *frequency*, so no changes are necessary to this structure.
```
    // Chosen assessment is the array of question banks and questions from the **state** object
    for (const node in chosenAssessment) {
        if (usedQuestionMap.has(node.id)) usedQuestionMap.set(node.id, 
            usedQuestionMap.get(node.id) + 1)
    }
```
