### ISSUE TITLE
Add private collections to Draft Manager

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#684]
The draft list can get pretty unwieldy for a large number of drafts. Need a way to organize these - either by folders, tags, or something that could compartmentalize and hide modules.

# Dashboard page changes:

- [x] `My Modules` heading becomes `My Recent Modules` only displaying 5-10(?) of the most recently updated modules.
- [x] Near `My Recent Modules` We need a new link or button to `All My Modules`
- [x] new route `/dashboard/modules` that shows *all* of a user's modules (basically what the current dashboard page looks like)

# Private collections (folders)

- [x] New section on dashboard for `My Collections`
- [x] New icon for representing a collection, probably some fancy box with 3 rounded corner hexagons on it
- [x] Each collection gets a url `/collections/my-url-safe-collection-name-<collection_id>
- [x] use `short-uuid` to shorten uuids for use in urls
- [ ] FUTURE problem: deal with a lot of collections
- [x] 'New... module' button has added option for 'new Collection', this button is displayed in all collections
- [x] Need a way to name and rename collections
- [x] collections are kept in the repository_collections table - probably using 'private' as a type
- [x] need a way to add a module to a collection

![IMG_20200203_171954](https://user-images.githubusercontent.com/73480/73697287-2b1f1d00-46ac-11ea-8652-9ecb5ff86099.jpg)

**Comment by FrenjaminBanklin** [comment]
Possible improvement: Instead of having three pages, keep everything contained to one and just modify the range of modules visible at any given time (i.e. start with 10, have a 'show me all of them' button nearby, replace the current range with all modules in a collection after clicking the collection, etc.). This would prevent cumbersome navigation/page loads.

If possible, it would be preferable if collections could be opened/closed for quick browsing or comparison.

**Comment by FrenjaminBanklin** [comment]
POST-DEMO IDEAS:

Rather than 'My Collections' being a horizontal dashboard area, make it a vertical sidebar - with 'recent modules' being a permanent fixture at the top

In the collection manage modules interface - when searching for modules, always list all results - just gray out modules that are in the collection already.

In the module manage collections interface - instead of the list area listing only the collections the module is in, have it list all available collections with a check box to the left side that indicates whether the module is in the collection or not. instead of a select field, have an input field that can be used to filter the collections that show up in the list below

In the api route - remove the check for collection ownership; let anybody see the collection list, and let the checks on the other API calls kick in to prevent them from doing anything

In the dashboard, only show 'My Collections' in the default splash screen that lists recent modules

In collection mode, have a static menu with any collection management actions

Add sort options to the 'My Collections' area
OR: Instead of implementing the collections and modules as two separate areas, have a single reusable 'list things that are sortable' component'

The folder icon will need to be replaced with something else

Re: storing collection management events - write relevant events to the log file on disk, make an issue that we can use to revisit later that'll address saving those events to a database table instead
