### ISSUE TITLE
Investigate LTI 1.3 and implement the new features it offers.

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#747]
https://community.canvaslms.com/thread/28177-lti-13-lti-advantage-documentation

https://www.youtube.com/watch?v=BjtoMk-1KcY

**Comment by Cvmcosta** [comment]
Hello, i came across this project because it uses the ims-lti framework ( more specifically express-ims-lti ). But this framework does not support the LTI 1.3 standard and it hasn't been maintained in about 4 years. 
I've recently started a project that implements the 1.3 version of the LTI protocol for tool providers in NodeJs. And since i'm conducting some research using this project i need all the feedback i can get. So it would be really nice if the maintainers could take a look and consider the viability of utilizing it. I could even implement it and submit a pull request for analysis if you're interested. The package is at [ltijs](https://cvmcosta.github.io/ltijs). 
Thanks in advance.

**Comment by iturgeon** [comment]
@Cvmcosta nice!  We don't currently have this issue attached to our roadmap, but it's obviously still something we plan on looking at.  You're welcome you taking a stab at it! 

Admittedly the project is a little complex and most of our experience on-boarding devs has been in house.  Most of the lti meat is in `obojobo-express/express_lti_launch.js` and and `obojobo-express/lti.js` 

We currently focus on supporting Instructure's Canvas, but are happy to integrate with more offerings.  

Currently, the only way to authenticate into the app is through LTI launches.  We typically use a development page (mounted at `/dev`) that simulates launches to the different end points we support.  We also use an LTI Tool emulator as needed.

It looks like ltijs requires Mongodb? How reasonable would it be to add PostgreSQL support? We currently have no plans to use or add Mongo to our stack.

**Comment by Cvmcosta** [comment]
@iturgeon Thanks for replying! PostgreSQL support is being implemented right now, and as soon as it's ready i'll come back and take a stab at it :).
